model:
  backbone: vit_b_16
  out_dim: 2048
loss:
  student_temp: 0.1
  teacher_temp: 0.04
  center_momentum: 0.9
  lambda1: 0.4
  lambda2: 1.6
  dino_norm_factor: 7.6
training:
  batch_size: 12
  learning_rate: 0.0002
  epochs: 100
  accumulate_grad_batches: 3
  num_workers: 4
  save_after: 10
  momentum: 0.996
  use_cosine_scheduler: false
  num_views: 4
data:
  train_path: /nfs/tier2/users/sm1367/Cell_Model/csv_creator/2d_ctc_train_dataset.csv
  val_path: /nfs/tier2/users/sm1367/Cell_Model/csv_creator/2d_ctc_test_dataset.csv
  out_path: /nfs/tier2/users/sm1367/Cell_Model/outputs
augmentation:
  random_resized_crop:
    scale: [0.5, 1.0]
    ratio: [0.75, 1.3333333333333333]
  hflip_prob: 0.5
  brightness_jitter: 0.6
  contrast_jitter: 0.6
  saturation_jitter: 0.6
  hue_jitter: 0.15
  gaussian_blur_prob: 0.3
  gaussian_blur:
    kernel_size: 3
    sigma: [0.1, 2.0]