model:
  backbone: vit_b_16
  out_dim: 8192
loss:
  student_temp: 0.07
  teacher_temp: 0.05
  center_momentum: 0.9
  lambda1: 1.0
  lambda2: 1.0
  dino_norm_factor: 9.0  # math.log(8192)
training:
  batch_size: 64  # Per GPU, total = 64 * 4 = 256
  learning_rate: 5e-4
  epochs: 100
  accumulate_grad_batches: 1
  num_workers: 4
  save_after: 10
  momentum: 0.996
  use_cosine_scheduler: false
data:
  train_path: /nfs/tier2/users/sm1367/Cell_Model/csv_creator/2d_ctc_train_dataset.csv
  val_path: /nfs/tier2/users/sm1367/Cell_Model/csv_creator/2d_ctc_test_dataset.csv
  out_path: /nfs/tier2/users/sm1367/Cell_Model/outputs
augmentation:
  random_resized_crop:
    scale: [0.5, 1.0]
    ratio: [0.75, 1.33]
  hflip_prob: 0.5
  brightness_jitter: 0.4
  contrast_jitter: 0.4
  saturation_jitter: 0.4
  hue_jitter: 0.1
  gaussian_blur_prob: 0.0